Type: Addin
Name: Cake.AppVeyor
NuGet: Cake.AppVeyor
Assemblies:
- "/**/Cake.AppVeyor.dll"
Repository: https://github.com/cake-contrib/Cake.AppVeyor/
Author: Jonathan Dick
Description: A set of aliases for Cake to access the AppVeyor REST API's
Categories:
- appveyor
TargetCakeVersion: 0.33.0
AnalyzedPackageVersion: 4.0.0
