Type: Addin
Name: Cake.XmlConfigStructureBuilder
NuGet: Cake.XmlConfigStructureBuilder
Assemblies:
- "/**/Cake.XmlConfigStructureBuilder.dll"
Repository: https://github.com/graph-uk/Cake.XmlConfigStructureBuilder/
Author: BggClr
Description: The project compiles multiple xml configs to single one using the CTT.
Categories:
- configs generator
- deployment
- environment
TargetCakeVersion: 0.33.0
AnalyzedPackageVersion: 1.3.2
